server:
    error:
        include-message: always
        include-stacktrace: never
        include-binding-errors: always
security:
    allowedOrigins: ${ALLOWED_ORIGINS}
    key: ${SECURITY_KEY}
    accessTokenMaxAge: 1200                 # 20 minutes in seconds
    refreshTokenMaxAge: 604800              # 7 days in seconds
    authCookieMaxAge: 604800
superuser:
    name: ${SUPERUSER_NAME}
    email: ${SUPERUSER_EMAIL}
    password: ${SUPERUSER_PASSWORD}
libsl:
    tempDir: ./temp/lsl
specificationPageSize: 10
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/lsldb
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    flyway:
        baseline-on-migrate: true
logging:
    level:
        web: trace
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    flyway:
        baseline-on-migrate: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
