server:
    error:
        include-message: always
        include-stacktrace: never
security:
    key: ${SECURITY_KEY}
    accessTokenMaxAge: 1200                 # 20 minutes in seconds
    refreshTokenMaxAge: 604800              # 7 days in seconds
superuser:
    name: ${SUPERUSER_NAME}
    email: ${SUPERUSER_EMAIL}
    password: ${SUPERUSER_PASSWORD}
libsl:
    tempDir: ./temp/lsl
specificationPageSize: 20
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:./temp/lsldb;AUTO_SERVER=true
        username: user
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    flyway:
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        baseline-on-migrate: true
    h2:
        console:
            enabled: true
logging:
    level:
        web: trace
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    flyway:
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        baseline-on-migrate: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
